name: Upload Variable

on:
  workflow_run:
    workflows: ["Update Variable"]
    types: [completed]
  workflow_dispatch:
    inputs:
      variable_name:
        description: 'Name of the variable to update'
        required: true
        default: 'REPO_VARIABLES'
      variable_value:
        description: 'New value for the variable'
        required: true
        default: 'Updated!'

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Upload Variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables/REPO_VARIABLES \
            -f name="REPO_VARIABLES" -f value="Updated"
          
          echo "Variable '$VARIABLE_NAME' has been updated to '$VARIABLE_VALUE'"
