name: Upload Variable

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Upload Variable
        env:
          GH_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables/REPO_VARIABLES \
            -f name="REPO_VARIABLES" -f value="Updated"
          
